@ExpenseTracker_API_HostAddress = http://localhost:5115
@ExpenseId = 00000000-0000-0000-0000-000000000000

GET {{ExpenseTracker_API_HostAddress}}/api/expenses
Accept: application/json

###

GET {{ExpenseTracker_API_HostAddress}}/api/expenses/{{ExpenseId}}
Accept: application/json

###

POST {{ExpenseTracker_API_HostAddress}}/api/expenses
Content-Type: application/json

{
	"amount": 12.50,
	"description": "Lunch",
	"photoUrl": null,
	"expenseDate": "2026-05-14T12:30:00Z"
}

###

PUT {{ExpenseTracker_API_HostAddress}}/api/expenses/{{ExpenseId}}
Content-Type: application/json

{
	"amount": 18.00,
	"description": "Dinner",
	"photoUrl": null,
	"expenseDate": "2026-05-14T18:00:00Z"
}

###

DELETE {{ExpenseTracker_API_HostAddress}}/api/expenses/{{ExpenseId}}
